/*
Copyright (C) 2011 GSyC/LibreSoft, Universidad Rey Juan Carlos.

Author: Jose Antonio Santos Cadenas <jcaden@libresoft.es>
Author: Santiago Carot-Nemesio <scarot@libresoft.es>

This program is a (FLOS) free libre and open source implementation
of a multiplatform manager device written in java according to the
ISO/IEEE 11073-20601. Manager application is designed to work in
DalvikVM over android platform.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

package ieee_11073.part_20601.asn1;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net
// Any modifications to this file will be lost upon recompilation of the source ASN.1.
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "ProdSpecEntry", isSet = false )
    public class ProdSpecEntry implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
            @ASN1ValueRangeConstraint (

		min = 0L,

		max = 65535L

	   )
        @ASN1Element ( name = "spec-type", isOptional =  false , hasTag =  false  , hasDefaultValue =  false, hasExplicitOrder = true, declarationOrder = 0  )

	private Integer spec_type = null;


        @ASN1Element ( name = "component-id", isOptional =  false , hasTag =  false  , hasDefaultValue =  false, hasExplicitOrder = true, declarationOrder = 1  )

	private PrivateOid component_id = null;

  @ASN1OctetString( name = "" )

        @ASN1Element ( name = "prod-spec", isOptional =  false , hasTag =  false  , hasDefaultValue =  false, hasExplicitOrder = true, declarationOrder = 2  )

	private byte[] prod_spec = null;



        public Integer getSpec_type () {
            return this.spec_type;
        }



        public void setSpec_type (Integer value) {
            this.spec_type = value;
        }



        public PrivateOid getComponent_id () {
            return this.component_id;
        }



        public void setComponent_id (PrivateOid value) {
            this.component_id = value;
        }



        public byte[] getProd_spec () {
            return this.prod_spec;
        }



        public void setProd_spec (byte[] value) {
            this.prod_spec = value;
        }




        public void initWithDefaults() {

        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(ProdSpecEntry.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
